### ISSUE TITLE
Move test files into the same directory as their script

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/javascript-reference#3]
1. Move tests found [here](https://github.com/baltimorecounty/javascript-reference/tree/master/test) into their corresponding folders above
1. Once this is done, we can remove the "test" folder

Example: 

Move [array-prototype-max.test.js](https://github.com/baltimorecounty/javascript-reference/blob/master/test/array/array-prototype-max.test.js) to the [array dir](https://github.com/baltimorecounty/javascript-reference/tree/master/01-array)

**Comment by mbelsky** [comment]
I'd like to do that

**Comment by martypowell** [comment]
@mbelsky go for it!

**Comment by martypowell** [comment]
resolved by @mbelsky  in #4
